kartik-v/bootstrap-fileinput

- README.md
- js/fileinput.js
Allow add custom headers to the request like "Authorization" header
> Expose current jqXHR object on "pre*" events

- js/fileinput.js
Fixed typo where "files" should be "tfiles". Caused "TypeError: files is undefined" error
> Fixed typo

- README.md
There was a link tag for loading javascript file. I have changed it to script tag.
> Wrong file in installation steps fixed

- js/fileinput_locale_ru.js
- js/fileinput_locale_uk.js
Added Ukrainian translation. And fixed some typos in the Russian translation
> Ukrainian translation + Russian translation fixes

- js/fileinput_locale_th.js
It's my very first contribution to GitHub.
Any mistake occurs please advise,
> add Thai language supported

- js/fileinput_locale_zh.js
> Create Chinese translations

- examples/index_pl.html
- js/fileinput_locale_pl.js
Polish translation of the current library.
> Add Polish translations

- js/fileinput_locale_tr.js
Hello,
I've added Turkish translation file.
> Add Turkish translation file.

- js/fileinput_locale_pt.js
Note: It is pt-PT (Portugal), for pt-BR (Brazil) there might be VERY slight variations on some words/terminology.
> Add Portuguese translation

- js/fileinput_locale_nl.js
> Add Dutch translations

- js/fileinput_locale_cz.js
- js/fileinput_locale_sk.js
> Add Czech & Slovakian translations

- js/fileinput_locale_el.js
Greek translation for kartik-v/bootstrap-fileinput
> Greek translation for kartik-v/bootstrap-fileinput

- js/fileinput_locale_uk.js
> Update Ukranian translations

- .gitignore
- js/fileinput.js
Hi, thank you for write this awesome plugin. But when i used it for upload files by ajax, i found it is useless to update `data.extra` field in `filepreupload` event handler. Maybe here is a little idea to improve it. I hope i use the right way to describe this. : )
> To support extra field update in filepreupload event handler

- js/fileinput_locale_da.js
> Add Danish translations

- js/fileinput_locale_ja.js
Japanese translation for kartik-v/bootstrap-fileinput
> Added Japanese translations

- js/fileinput_locale_ar.js
Thanks for this great plugin, I have translated it into Arabic **100%**.
> Add Arabic Translations

- js/fileinput_locale_ca.js
> Add Català translations

- js/fileinput_locale_fi.js
JS type error fixed with finnish localization
> Correct Finnish Localizations

- js/locales/es.js
> Update Spanish translations

- sass/fileinput.scss
It would be nice to have a sass file in order to change some variable, here is the first shot.
What do you think about this ?
> Include sass styling configuration

- js/fileinput.js
> Wrong order in argument to "_renderFileActions"

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
> Update Turkish Translations

- js/locales/ru.js
> Update Russian Translations

- js/locales/zh.js
> Update Chinese translations

- js/locales/sl.js
- Added Slovenian language
Added slovenian translation
> Added Slovenian Translations

- js/locales/kr.js
> Add Korean Translations

- js/locales/fi.js
- [X ] Translation
- Improve finnish translations
> Improve finnish translations

- js/locales/de.js
- Translation
- set "msgNoFilesSelected" in german local (de)
> Update German Translations

- js/locales/kz.js
> Create Kazakh Translations

- js/locales/sv.js
> Add Swedish Translations

- examples/index.html
- js/locales/es.js
- js/locales/gl.js
Fixed locale es
Fixed import es and fr in example index.html
Add locale gl
> Fixed locales

- js/locales/no.js
Added norwegian language file.
- Added norwegian translation file.
> Add Norwegian Translations

- js/locales/et.js
> Add Estonian Translations

- sass/fileinput.scss
- Added a SASS variable to specify the path for all image assets.
> Added image path variable

- js/locales/fa.js
- [x ] Translation
- correcting a mistake on translation.
> Update Farsi Translations

- js/locales/pt-BR.js
- Translated to pt-BR the labels that were still in English and one (indicatorLoadingTitle) that was more like pt-PT than pt-BR
No related issues
> Updates to Portugese BR translations

- js/locales/pt-BR.js
Text for the previously blank `msgNoFilesSelected` label was set (missed it in the previous pr).
No related issues
> Update Portugese BR translations

- js/locales/lt.js
> Added Lithuanian translations

- js/locales/it.js
> Update Italian translations

- js/locales/ka.js
- Added Georgian (ka) translations
> Add Georgian locale

- README.md
- Adding correct path to File Input translation files
-
-
> Fixing Translation path

- js/locales/pt-BR.js
Translation error correction for pt-BR.
> Update Portuguese Brazilian translations

- js/locales/sk.js
- [ x] Translation
- Update Slovak translation
> Update Slovak Translations

- js/locales/cs.js
- [ x] Translation
- Update Czech translation
> Update Czech Translations

- themes/fas/theme.js
- themes/fas/theme.min.js
- Added a Font Awesome 5 theme file
- Remapped some icon names with new names
None
> Font Awesome 5 Theme

- js/locales/he.js
> Add Hebrew Translations

- js/locales/nl.js
- [X ] Translation
WAS: Select {files}
IS: Selecteer {files}
-
-
> Update Dutch Translations

- js/locales/he.js
Added the 'msgPlaceholder' translation
- Added translation for 'msgPlaceholder'
-
-
> Update Hebrew Translations

- js/fileinput.js
Reverts kartik-v/bootstrap-fileinput#1524
> Revert "TabIndex of 500 is illegal as per AODA, it has been changed to 0"

- js/locales/sr-latn.js
This is the translation for the Serbian latin. If possible, please add it to your next release since Im waiting for it because of the textarea form submit fix.
Thank you
- New translation js file for Serbian latin.
> Add Serbian Latin Translations

- js/locales/el.js
- Minor typos fixed for Greek.
> Update Greek Translations

- js/locales/lv.js
- Added Latvian Translation file to  js/locales
> Added Latvian Translations

- scss/fileinput.scss
- [x ] Bug fix
- fix sass-compilation error
> fix SassError Invalid parent selector

- js/fileinput.js
> add image/vnd.dwg signature

- js/locales/ur.js
> Create Urdu Translations

- js/locales/eu.js
- Location Basque (eu, eu_ES)
It is an automatic translation.
> Location Basque (eu, eu_ES)

- js/locales/ms.js
- [/ ] Translation
- add a new file in /js/locales/ named ms.js for Bahasa Melayu with code ms
> Language translation to Bahasa Melayu

- js/fileinput.js
- described in issue
https://github.com/kartik-v/bootstrap-fileinput/issues/1874
> Plugin localization didn't fallback to language if locale is specified
