js/fileinput_locale_tr.js
Sorry dude, didn't notice this in my previous pull request.
=> Escape the errorous single quote in msgSizeTooLarge.

bower.json, composer.json
The license identifiers should conform to the SPDX Open Source License Registry entries. Right now some tools like Webjars will fail due to the mismatch of license tag.
=> Fixed license identifiers in bower.json and composer.json.

js/fileinput_locale_hu.js
Hi Kartik,
Plural for files is really "fájlok" in Hungarian, but the plural form does not make sense in the sentence it is currently used.
"2 files selected" in Hungarian is: "2 fájl kiválasztva".
Please update it.
Thanks!
Sly
=> Update Hungarian translations

package.json
After this patch `jquery` and `bootstrap` are removed from the `dependencies` section of `package.json` and they're granted `peerDependencies` status instead of it.
Rationale:
* All of these three packages (`bootstrap-fileinput`, `bootstrap`, `jquery`) are quite likely to be defined as dependencies of their common parent application (which is, most likely, a web site; could also be an application built on [Electron](http://electron.atom.io/), [NW.js](http://nwjs.io/), [JXcore for Cordova](https://github.com/jxcore/jxcore-cordova/), etc.) and thus to become peers in that sense. Currently, if some version mismatch happens on that level (under that parent), `npm` would install another version of `bootstrap` or `jquery` under `bootstrap-fileinput` (and that would be the versions required …
=> `jquery` and `bootstrap`: `peerDependencies` ← `dependencies`

js/fileinput.js
We have to clean the tags array too.
There is a problem when we upload a file, delete the file, and upload another file, the tags are the same than the first file uploaded. Only occurs when we have custom layoutTemplates and previewThumbTags.
=> Fixed unset method used for delete a previewCache index

js/fileinput_locale_de.js
This change fixes the displayed text when choosing a file which doesn't match the allowed file types (or other criteria).
The old incorrect text `"Nein Dateien ausgewählt"` now displays as `"Keine Dateien ausgewählt"` with this fix.
=> Update German Translations

js/fileinput.js
For IE9 only find the correct name for the file to be uploaded as this.$element.files does not exist
=> Find correct filename in IE9

package.json
So I can just do `require('bootstrap-fileinput')` in nodejs to use it.
=> Add ability to just require package in nodejs

js/fileinput.js
My site have Content Security Policy (CSP) enabled with ```script-src: self 'unsafe-inline' ```
In Chrome I have CSP error after selecting a file.
> Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive
I had to wrap both readFile(...) in the setTimeout() with a function(){} to make it work.
Source : https://developer.chrome.com/extensions/contentSecurityPolicy
=> Wrap readFile(index + 1) in a function to prevent 'unsafe-eval' blocking with CSP

js/locales/vi.js
=> Add Vietnamese translations

js/fileinput.js
After calling `cancel()` `self.ajaxAborted` becomes undefined, therefore `self.ajaxAborted.message` throws an error.
- Fix the abort function, so when there is a client validation failure the message gets properly displayed.
=> Cancel after self fields are used.

js/locales/pt-BR.js
"Select" don't exist in portuguese, the correct translation is "Selecionar"
-
-
-
=> Change Select to Selecionar

js/fileinput.js
- [x ] New feature
-Changed TabIndex of 0 to 500, as per AODA regulation
=> TabIndex of 500 is illegal as per AODA, it has been changed to 0

js/fileinput.js
- Handle file read abort, then restore initial state before file read
#1525
=> Fix #1525: Handle filebeforeload event abort when returning false

js/fileinput.js
- parse json answer to String object
#1536
=> Fix #1536: Parse response as string in `_parseError` function

js/fileinput.js
- general progress bar would not stay on cancelled status because of a set timeout on fnComplete
removing setTimeout on fnComplete because it is not usefull to do so
- rm is undefined on async upload (not resumable)
check rm before assigning pool, this is because self.resumableManager is undefined in that case
so it would throw an unhandled error
Did no open an issue but this happens  on this conditions
Set async uploads but not resumable :
- uploadAsync: true,
- enableResumableUpload: false, 
Then force the upload to fail (server always return 500 for ex), it will throw ```rm is undefined```
Then chunkComplete would happen when upload is cancelled, and the …
=> Correct timeout and resumable validation for async uploads

js/fileinput.js
Since `Function()` is considered same as eval.
You cannot parse JS without triggering unsafe-eval.
There is no way to bypass this either you force unsafe-inline, unsafe-eval or just disable JS inline event from templates.
The third option seems to be the only solution.
Also your site would need to be updated to remove inline-script (onpaste ..)
https://plugins.krajee.com/file-input/plugin-options
- remove inline script form template (caption name)
- disable click and paste with jquery event ( return false ) instead of inline script from template
- remove inline-script from CSP buffer
#1612
=>  Fix #1612: Remove unsupported script-inline from template and CSP buffer

js/fileinput.js
https://github.com/kartik-v/bootstrap-fileinput/issues/1652
- [x ] Bug fix
-
-
-
=> Fix #1652: Correct error for preupload event when showPreview is false 

js/locales/da.js
Missing jquery dependancy injection. Webpack fails compiling because of unmatched round brackets
- added jquery dependancy injection and fixed unmatching round brackets
=> syntax error on danish translations

js/fileinput.js
Adding default options  override option for:
$.extend($.fn.fileinput.defaults, {theme: 'fa4'});
-
-
-
=> Update fileinput.js overriding default options 

js/fileinput.js
I made this to allow developers to set also max file size when we pick multiiple files, to set up, you must provide new parameter called: "maxMultipleFileSize"
- new parameter "maxMultipleFileSize" was added to allow developers to set max files size for multiple files 
- is possíble to see preview error for multiple files, when their full size exceeds what was configured
- https://github.com/kartik-v/bootstrap-fileinput/issues/1849
=> Define max files size for input[multiple] - when pick multiple files
